import {
  clearSession,
  getAccessToken,
  setSession,
} from "#/feature/auth/store";
import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

/** `include` is required for the httpOnly refresh cookie: the API is a different origin. */
export const apiClient = createClient<paths>({
  baseUrl: import.meta.env.VITE_API_URL,
  credentials: "include",
});

/**
 * Endpoints that carry no access token. `/api/auth/refresh` is the load-bearing
 * entry: excluding it stops its own 401 from triggering another refresh.
 */
const PUBLIC_PATHS = new Set<string>([
  "/api/health",
  "/api/auth/login",
  "/api/auth/register",
  "/api/auth/refresh",
  "/api/auth/github",
]);

const isServer = () => typeof window === "undefined";

let refreshing: Promise<boolean> | null = null;

async function requestRefresh(): Promise<boolean> {
  const { data } = await apiClient.POST("/api/auth/refresh");

  try {
    setSession(data);
    return true;
  } catch {
    clearSession();
    return false;
  }
}

/**
 * Mints a new access token from the refresh cookie.
 *
 * Concurrent callers share one in-flight promise, so a burst of 401s produces a
 * single refresh request instead of a storm. Always false on the server, where
 * the browser's cookie never reaches us.
 */
export function ensureRefreshed(): Promise<boolean> {
  if (isServer()) return Promise.resolve(false);

  refreshing ??= requestRefresh().finally(() => {
    refreshing = null;
  });

  return refreshing;
}

/**
 * Pre-send copies of in-flight requests, keyed by the id openapi-fetch assigns
 * to each call. A `Request` body is a stream that can only be read once, so a
 * retry needs a clone taken before the original was sent.
 */
const retryable = new Map<string, Request>();

const authMiddleware: Middleware = {
  onRequest({ request, schemaPath, id }) {
    if (PUBLIC_PATHS.has(schemaPath)) return undefined;

    if (!isServer()) {
      retryable.set(id, request.clone());
    }

    const accessToken = getAccessToken();
    if (accessToken) {
      request.headers.set("Authorization", `Bearer ${accessToken}`);
    }

    return request;
  },

  /** Turns an expired-token 401 into a refresh plus one silent retry. */
  async onResponse({ response, id }) {
    const original = retryable.get(id);
    retryable.delete(id);

    if (response.status !== 401 || !original) return response;

    if (!(await ensureRefreshed())) return response;

    original.headers.set("Authorization", `Bearer ${getAccessToken()}`);

    // Plain fetch, not apiClient — the retry must not re-enter this middleware.
    return fetch(original);
  },

  /** A thrown fetch never reaches onResponse, so drop the clone here instead. */
  onError({ id }) {
    retryable.delete(id);
  },
};

apiClient.use(authMiddleware);
